import { useEffect, useState } from "preact/hooks";
import type { DesignerWorkflowSummary, DesignerStoredWorkflow, DesignerWorkflowStep, DesignerStepKind, ActivityCatalogItem, DesignerWeekday, IntegrationStatusItem } from "../../api/types";
import {
  getDesignerWorkflows,
  getDesignerWorkflow,
  createDesignerWorkflow,
  updateDesignerWorkflow,
  getActivitiesCatalog,
  getIntegrationsStatus,
  postDesignerTestRun,
  getDesignerTemplates,
  getDesignerTemplate,
  updateDesignerTemplate,
  restoreDesignerTemplate,
  createWorkflowFromTemplate,
} from "../../api/designer";
import { TIMEZONES, TIMEZONE_LABELS, WEEKDAY_LABELS } from "./constants";
import { buildDefaultInputFromSchema, formatHM, parseHM, scheduleSummary } from "./helpers";
import { slugifyProcessName, uniqueProcessId } from "./slug";
import { STEP_BLOCK_OPTIONS, stepDisplayLabel } from "./step-labels";
import { credentialsPathForIntegration } from "../credentials/providerSchemas";
import { useUiText } from "../../i18n";
import type { DesignerTemplateSummary } from "../../api/types";

const EMPTY_WORKFLOW: DesignerStoredWorkflow = {
  id: "",
  version: "v1",
  displayName: "",
  description: "",
  tags: [],
  schedule: { type: "instant" },
  scheduledInput: {},
  inputSchema: undefined,
  resultSchema: undefined,
  steps: [],
  entryStepId: "",
};

export function DesignerPage() {
  const { t } = useUiText();
  type Mode = "list" | "edit";
  type EditTarget = "workflow" | "template";
  type WizardStep = 1 | 2 | 3;

  const [activities, setActivities] = useState<ActivityCatalogItem[]>([]);
  const [loadingActivities, setLoadingActivities] = useState(false);
  const [activitiesError, setActivitiesError] = useState<Error | null>(null);
  const [integrationsStatus, setIntegrationsStatus] = useState<IntegrationStatusItem[]>([]);
  const [integrationsStatusError, setIntegrationsStatusError] = useState<Error | null>(null);

  const [mode, setMode] = useState<Mode>("list");
  const [workflows, setWorkflows] = useState<DesignerWorkflowSummary[]>([]);
  const [loadingList, setLoadingList] = useState(false);
  const [errorList, setErrorList] = useState<Error | null>(null);

  const [current, setCurrent] = useState<DesignerStoredWorkflow | null>(null);
  const [loadingCurrent, setLoadingCurrent] = useState(false);
  const [errorCurrent, setErrorCurrent] = useState<Error | null>(null);
  const [schedInputDraft, setSchedInputDraft] = useState("{}");
  const [schedInputJsonError, setSchedInputJsonError] = useState<string | null>(null);
  const [testRunMessage, setTestRunMessage] = useState<string | null>(null);
  const [testRunLoading, setTestRunLoading] = useState(false);
  const [templateError, setTemplateError] = useState<string | null>(null);
  const [templates, setTemplates] = useState<DesignerTemplateSummary[]>([]);
  const [loadingTemplates, setLoadingTemplates] = useState(false);
  const [templatesError, setTemplatesError] = useState<Error | null>(null);
  const [editTarget, setEditTarget] = useState<EditTarget>("workflow");
  const [editingTemplateId, setEditingTemplateId] = useState<string | null>(null);
  const [wizardStep, setWizardStep] = useState<WizardStep>(1);
  const [advancedMode, setAdvancedMode] = useState(false);
  const [idAutoGenerated, setIdAutoGenerated] = useState(true);
  const [actionMessage, setActionMessage] = useState<string | null>(null);

  useEffect(() => {
    setLoadingActivities(true);
    getActivitiesCatalog()
      .then(setActivities)
      .catch((e) => setActivitiesError(e as Error))
      .finally(() => setLoadingActivities(false));
  }, []);

  useEffect(() => {
    setIntegrationsStatusError(null);
    getIntegrationsStatus()
      .then(setIntegrationsStatus)
      .catch((e) => setIntegrationsStatusError(e as Error));
  }, []);

  useEffect(() => {
    setLoadingTemplates(true);
    setTemplatesError(null);
    getDesignerTemplates()
      .then(setTemplates)
      .catch((e) => setTemplatesError(e as Error))
      .finally(() => setLoadingTemplates(false));
  }, []);

  useEffect(() => {
    setLoadingList(true);
    setErrorList(null);
    getDesignerWorkflows()
      .then(setWorkflows)
      .catch((e) => setErrorList(e as Error))
      .finally(() => setLoadingList(false));
  }, []);

  function reloadLists() {
    return Promise.all([getDesignerWorkflows().then(setWorkflows), getDesignerTemplates().then(setTemplates)]);
  }

  function handleNew() {
    setCurrent(structuredClone(EMPTY_WORKFLOW));
    setErrorCurrent(null);
    setTemplateError(null);
    setActionMessage(null);
    setSchedInputDraft("{}");
    setEditTarget("workflow");
    setEditingTemplateId(null);
    setWizardStep(1);
    setAdvancedMode(false);
    setIdAutoGenerated(true);
    setMode("edit");
  }

  function missingActivitiesForTemplate(template: DesignerTemplateSummary): string[] {
    const available = new Set(activities.map((a) => a.name));
    return (template.requiredActivities ?? []).filter((name) => !available.has(name));
  }

  async function handleEditTemplate(id: string) {
    setLoadingCurrent(true);
    setErrorCurrent(null);
    setActionMessage(null);
    try {
      const tpl = await getDesignerTemplate(id);
      const wf = structuredClone(tpl.payload);
      setCurrent(wf);
      setEditTarget("template");
      setEditingTemplateId(id);
      setWizardStep(1);
      setAdvancedMode(false);
      setIdAutoGenerated(false);
      try {
        setSchedInputDraft(JSON.stringify(wf.scheduledInput ?? {}, null, 2));
      } catch {
        setSchedInputDraft("{}");
      }
      setMode("edit");
    } catch (e) {
      setErrorCurrent(e as Error);
    } finally {
      setLoadingCurrent(false);
    }
  }

  async function handleRestoreTemplate() {
    if (!editingTemplateId) return;
    setErrorCurrent(null);
    try {
      await restoreDesignerTemplate(editingTemplateId);
      await handleEditTemplate(editingTemplateId);
      await reloadLists();
      setActionMessage(t.designer.restoreTemplate);
    } catch (e) {
      setErrorCurrent(e as Error);
    }
  }

  async function handleCreateProcessFromTemplate() {
    if (!editingTemplateId || !current) return;
    setErrorCurrent(null);
    try {
      const existing = new Set(workflows.map((w) => w.id));
      const newId = uniqueProcessId(current.displayName || editingTemplateId, existing);
      await createWorkflowFromTemplate(editingTemplateId, {
        id: newId,
        displayName: current.displayName || undefined,
      });
      await reloadLists();
      setActionMessage(t.designer.processCreatedFromTemplate);
      handleEdit(newId);
    } catch (e) {
      setErrorCurrent(e as Error);
    }
  }


  function handleEdit(id: string) {
    setLoadingCurrent(true);
    setErrorCurrent(null);
    setActionMessage(null);
    getDesignerWorkflow(id)
      .then((wf) => {
        const normalized: DesignerStoredWorkflow = {
          ...wf,
          schedule: wf.schedule ?? { type: "instant" },
          scheduledInput: wf.scheduledInput ?? {},
        };
        setCurrent(normalized);
        setEditTarget("workflow");
        setEditingTemplateId(null);
        setWizardStep(1);
        setAdvancedMode(false);
        setIdAutoGenerated(false);
        try {
          const inj = JSON.stringify(normalized.scheduledInput ?? {}, null, 2);
          setSchedInputDraft(inj);
        } catch {
          setSchedInputDraft("{}");
        }
        setMode("edit");
      })
      .catch((e) => setErrorCurrent(e as Error))
      .finally(() => setLoadingCurrent(false));
  }

  async function handleSave() {
    if (!current){
        return;
    }
    
    try {
      setErrorCurrent(null);
      if (!current.id) {
        throw new Error("El campo 'id' es obligatorio");
      }
      if (!current.displayName) {
        throw new Error("El campo 'displayName' es obligatorio");
      }
      if (!current.version) {
        throw new Error("El campo 'version' es obligatorio");
      }
      if (!current.steps.length) {
        throw new Error("Debe haber al menos un step");
      }
      if (!current.entryStepId || !current.steps.some((s) => s.id === current.entryStepId)) {
        throw new Error("entryStepId debe ser el id de un step existente");
      }

      const sched = current.schedule ?? { type: "instant" as const };
      if (sched.type === "weekly" && (!sched.weekdays || sched.weekdays.length === 0)) {
        throw new Error("En ejecución semanal elige al menos un día");
      }

      let scheduledInput: unknown = {};
      try {
        scheduledInput = schedInputDraft.trim() === "" ? {} : JSON.parse(schedInputDraft);
      } catch {
        throw new Error("Input programado: JSON inválido");
      }

      const toSave: DesignerStoredWorkflow = {
        ...current,
        schedule: sched,
        scheduledInput,
        entryStepId: current.steps[0]?.id ?? current.entryStepId,
      };

      if (editTarget === "template" && editingTemplateId) {
        await updateDesignerTemplate(editingTemplateId, {
          payload: toSave,
          label: toSave.displayName,
          description: toSave.description,
        });
        await reloadLists();
        setActionMessage(t.designer.saveTemplate);
        return;
      }

      if (workflows.some((w) => w.id === current.id)) {
        await updateDesignerWorkflow(current.id, toSave);
      } else {
        await createDesignerWorkflow(toSave);
      }

      await reloadLists();
      setMode("list");
      setCurrent(null);
    } catch (e) {
      setErrorCurrent(e as Error);
    }
  }

  function updateCurrent(updater: (prev: DesignerStoredWorkflow) => DesignerStoredWorkflow) {
    setCurrent((prev) => (prev ? updater(prev) : prev));
  }

  function handleAddStep() {
    if (!current) return;
    const newId = `step-${current.steps.length + 1}`;
    const newStep: DesignerWorkflowStep = {
      id: newId,
      kind: "activity",
      activityName: "",
      input: {},
      next: null,
    } as any;
    updateCurrent((prev) => ({
      ...prev,
      steps: [...prev.steps, newStep],
      entryStepId: prev.entryStepId || newId,
    }));
  }

  function handleRemoveStep(id: string) {
    if (!current) return;
    updateCurrent((prev) => {
      const steps = prev.steps.filter((s) => s.id !== id);
      const entryStepId = prev.entryStepId === id ? (steps[0]?.id ?? "") : prev.entryStepId;
      const fixedSteps = steps.map((s) => ({
        ...s,
        next: s.next === id ? null : s.next,
      }));
      return { ...prev, steps: fixedSteps, entryStepId };
    });
  }

  function handleStepFieldChange(id: string, field: string, value: any) {
    if (!current) return;
    updateCurrent((prev) => ({
      ...prev,
      steps: prev.steps.map((s) => (s.id === id ? { ...s, [field]: value } : s)),
    }));
  }

  function handleStepKindChange(id: string, kind: DesignerStepKind) {
    if (!current) return;
    updateCurrent((prev) => ({
      ...prev,
      steps: prev.steps.map((s) => {
        if (s.id !== id) return s;
        if (kind === "activity") {
          return { ...s, kind, activityName: (s as any).activityName ?? "", input: (s as any).input ?? {} } as any;
        }
        if (kind === "sleep") {
          return { ...s, kind, milliseconds: (s as any).milliseconds ?? 1000 } as any;
        }
        if (kind === "signal") {
          return { ...s, kind, signalName: (s as any).signalName ?? "signal-name" } as any;
        }
        if (kind === "conditional") {
          return { ...s, kind, expression: (s as any).expression ?? "input.amount > 0", thenNext: (s as any).thenNext ?? null, elseNext: (s as any).elseNext ?? null } as any;
        }
        if (kind === "retry") {
          return {
            ...s,
            kind,
            maxAttempts: typeof (s as any).maxAttempts === "number" ? (s as any).maxAttempts : 3,
            backOffMs: typeof (s as any).backOffMs === "number" ? (s as any).backOffMs : undefined,
            targetStepId: typeof (s as any).targetStepId === "string" ? (s as any).targetStepId : "",
          } as any;
        }
        return { ...s, kind, branches: Array.isArray((s as any).branches) ? (s as any).branches : [[]] } as any;
      }),
    }));
  }

  return (
    <div class="app-layout designer-page">
      <div class="sidebar">
        <div class="panel">
          <h2 class="panel-title">{t.designer.title}</h2>
          {loadingActivities && <p class="detail-muted">{t.designer.loadingActivities}</p>}
          {activitiesError && <p class="panel panel-error">Activities: {activitiesError.message}</p>}
          {templateError && <p class="panel panel-error">{templateError}</p>}
          <div class="integration-status">
            <div class="integration-status-title">{t.designer.integrationsStatus}</div>
            {integrationsStatusError ? (
              <p class="detail-muted">
                {t.designer.integrationsStatusLoadFailed} {integrationsStatusError.message}
              </p>
            ) : integrationsStatus.length === 0 ? (
              <p class="detail-muted">{t.designer.integrationsStatusEmpty}</p>
            ) : (
              <ul class="integration-status-list">
                {integrationsStatus.map((s) => {
                  const configureHref = !s.configured ? credentialsPathForIntegration(s.key) : undefined;
                  return (
                  <li key={s.key} class={`integration-status-item ${s.configured ? "ok" : "missing"}`}>
                    <span>{s.label}</span>
                    <span>
                      {s.configured ? (
                        `OK (${s.source})`
                      ) : configureHref ? (
                        <a class="integration-status-configure" href={configureHref}>
                          {t.designer.configureIntegration}
                        </a>
                      ) : (
                        t.designer.missing
                      )}
                    </span>
                  </li>
                  );
                })}
              </ul>
            )}
          </div>
          <button type="button" class="workflow-filter-btn" onClick={handleNew}>
            {t.designer.newProcess}
          </button>
          <h3 class="designer-sidebar-heading">{t.designer.myTemplates}</h3>
          {loadingTemplates ? (
            <p class="detail-muted">{t.designer.loading}</p>
          ) : templatesError ? (
            <p class="panel panel-error">{templatesError.message}</p>
          ) : templates.length === 0 ? (
            <p class="detail-muted">{t.designer.noTemplatesYet}</p>
          ) : (
            <ul class="workflow-list designer-template-list">
              {templates.map((tpl) => {
                const missing = missingActivitiesForTemplate(tpl);
                return (
                  <li
                    key={tpl.id}
                    class="workflow-list-item"
                    onClick={() => {
                      if (missing.length > 0) {
                        setTemplateError(t.designer.templateRequires(tpl.label, missing.join(", ")));
                        return;
                      }
                      setTemplateError(null);
                      void handleEditTemplate(tpl.id);
                    }}
                    style={{ cursor: "pointer" }}
                  >
                    <div class="workflow-name">
                      {missing.length > 0 ? `⚠ ${tpl.label}` : tpl.label}
                    </div>
                    <div class="workflow-meta">
                      <span>{tpl.isCustom ? t.designer.templateCustom : t.designer.templateOriginal}</span>
                    </div>
                    <div class="detail-muted" style={{ fontSize: "11px", marginTop: "4px" }}>
                      {tpl.description}
                    </div>
                  </li>
                );
              })}
            </ul>
          )}
          <h3 class="designer-sidebar-heading">{t.designer.myProcesses}</h3>
          <p class="detail-muted" style={{ marginTop: "4px", marginBottom: "8px" }}>
            {t.designer.templatesRequireRegistered}
          </p>
          {loadingList ? (
            <p class="detail-muted">{t.designer.loading}</p>
          ) : errorList ? (
            <p class="panel panel-error">
              {t.designer.errorPrefix} {errorList.message}
            </p>
          ) : workflows.length === 0 ? (
            <p class="workflow-list-empty">{t.designer.noWorkflowsYet}</p>
          ) : (
            <ul class="workflow-list">
              {workflows.map((w) => (
                <li
                  key={w.id}
                  class="workflow-list-item"
                  onClick={() => handleEdit(w.id)}
                  style={{ cursor: "pointer" }}
                >
                  <div class="workflow-name">{w.displayName || w.id}</div>
                  <div class="workflow-meta">
                    <span>{w.id}</span> · <span>v{w.version}</span>
                  </div>
                  <div class="detail-muted" style={{ fontSize: "11px", marginTop: "4px" }}>
                    {scheduleSummary(w.schedule)}
                  </div>
                  {w.lastScheduledRunAt ? (
                    <div class="detail-muted" style={{ fontSize: "11px", marginTop: "2px" }}>
                      {t.designer.lastRun} {new Date(w.lastScheduledRunAt).toLocaleString()}
                    </div>
                  ) : null}
                  {w.lastScheduledError ? (
                    <div class="panel panel-error" style={{ marginTop: "6px", fontSize: "11px" }}>
                      {t.designer.lastError} {w.lastScheduledError}
                    </div>
                  ) : null}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      <div class="content">
        {mode === "edit" ? (
          <div class="panel">
            <h2 class="panel-title">
              {editTarget === "template" ? t.designer.editTemplate : t.designer.editWorkflow}
            </h2>
            {actionMessage && <p class="detail-muted">{actionMessage}</p>}
            <div class="designer-wizard-nav">
              {([1, 2, 3] as WizardStep[]).map((step) => (
                <button
                  key={step}
                  type="button"
                  class={wizardStep === step ? "workflow-filter-btn active" : "workflow-filter-btn"}
                  onClick={() => setWizardStep(step)}
                >
                  {step === 1 ? t.designer.wizardStep1 : step === 2 ? t.designer.wizardStep2 : t.designer.wizardStep3}
                </button>
              ))}
              <button
                type="button"
                class="workflow-filter-btn"
                onClick={() => setAdvancedMode((v) => !v)}
              >
                {t.designer.advancedMode}
              </button>
            </div>
            {editTarget === "template" && (
              <div class="designer-template-actions" style={{ marginBottom: "12px" }}>
                <button type="button" class="workflow-filter-btn" onClick={() => void handleCreateProcessFromTemplate()}>
                  {t.designer.createProcessFromTemplate}
                </button>
                <button type="button" class="workflow-filter-btn" onClick={() => void handleRestoreTemplate()}>
                  {t.designer.restoreTemplate}
                </button>
              </div>
            )}
            {loadingCurrent && <p class="detail-muted">{t.designer.loading}</p>}
            {errorCurrent && (
              <p class="panel panel-error">
                {t.designer.errorPrefix} {errorCurrent.message}
              </p>
            )}
            {current && (
              <>
                {wizardStep === 1 && (
                <section class="workflow-section workflow-section--meta">
                  <h3>{t.designer.meta}</h3>
                  <div class="form-row">
                    <label>{t.designer.processName}</label>
                    <input
                      type="text"
                      value={current.displayName}
                      onInput={(e) => {
                        const displayName = (e.target as HTMLInputElement).value;
                        updateCurrent((prev) => {
                          const next = { ...prev, displayName };
                          if (editTarget === "workflow" && idAutoGenerated) {
                            const existing = new Set(workflows.map((w) => w.id));
                            next.id = uniqueProcessId(displayName || "proceso", existing);
                          }
                          return next;
                        });
                      }}
                    />
                  </div>
                  {editTarget === "workflow" && (
                    <div class="form-row">
                      <label>{t.designer.processCode}</label>
                      <input
                        type="text"
                        value={current.id}
                        onInput={(e) => {
                          setIdAutoGenerated(false);
                          updateCurrent((prev) => ({ ...prev, id: (e.target as HTMLInputElement).value }));
                        }}
                        disabled={workflows.some((w) => w.id === current.id)}
                      />
                      {idAutoGenerated && <p class="detail-muted">{t.designer.processCodeHint}</p>}
                    </div>
                  )}
                  <div class="form-row">
                    <label>{t.designer.description}</label>
                    <textarea
                      value={current.description ?? ""}
                      onInput={(e) =>
                        updateCurrent((prev) => ({
                          ...prev,
                          description: (e.target as HTMLTextAreaElement).value,
                        }))
                      }
                    />
                  </div>
                  <div class="form-row">
                    <label>{t.designer.tags}</label>
                    <input
                      type="text"
                      value={(current.tags ?? []).join(", ")}
                      onInput={(e) => {
                        const raw = (e.target as HTMLInputElement).value;
                        const tags = raw
                          .split(",")
                          .map((t) => t.trim())
                          .filter(Boolean);
                        updateCurrent((prev) => ({ ...prev, tags }));
                      }}
                    />
                  </div>
                  {advancedMode && (
                    <div class="form-row">
                      <label>{t.designer.version}</label>
                      <input
                        type="text"
                        value={current.version}
                        onInput={(e) =>
                          updateCurrent((prev) => ({ ...prev, version: (e.target as HTMLInputElement).value }))
                        }
                      />
                    </div>
                  )}
                </section>
                )}

                {wizardStep === 2 && (
                <section class="workflow-section workflow-section--meta">
                  <h3>{t.designer.execution}</h3>
                  <p class="detail-muted">
                    {t.designer.usedForInstantAndScheduled}
                  </p>
                  <div class="form-row">
                    <label>{t.designer.execution}</label>
                    <select
                      value={current.schedule?.type ?? "instant"}
                      onInput={(e) => {
                        const v = (e.target as HTMLSelectElement).value;
                        updateCurrent((prev) => {
                          if (v === "instant") {
                            return { ...prev, schedule: { type: "instant" } };
                          }
                          if (v === "daily") {
                            return {
                              ...prev,
                              schedule: {
                                type: "daily",
                                hour: 9,
                                minute: 0,
                                timezone: "Europe/Madrid",
                              },
                            };
                          }
                          return {
                            ...prev,
                            schedule: {
                              type: "weekly",
                              weekdays: [0, 1, 2, 3, 4],
                              hour: 9,
                              minute: 0,
                              timezone: "Europe/Madrid",
                            },
                          };
                        });
                      }}
                    >
                      <option value="instant">{t.designer.whenManual}</option>
                      <option value="daily">{t.designer.whenDaily}</option>
                      <option value="weekly">{t.designer.whenWeekly}</option>
                    </select>
                  </div>
                  <div class="form-row">
                    <label>{t.designer.timezone}</label>
                    <select
                      value={
                        current.schedule?.type === "instant"
                          ? "UTC"
                          : (current.schedule?.timezone ?? "UTC")
                      }
                      disabled={current.schedule?.type === "instant"}
                      onInput={(e) => {
                        const tz = (e.target as HTMLSelectElement).value;
                        updateCurrent((prev) => {
                          const s = prev.schedule;
                          if (!s || s.type === "instant") return prev;
                          return { ...prev, schedule: { ...s, timezone: tz } };
                        });
                      }}
                    >
                      {TIMEZONES.map((tz) => (
                        <option key={tz} value={tz}>
                          {TIMEZONE_LABELS[tz] ?? tz}
                        </option>
                      ))}
                    </select>
                  </div>
                  {current.schedule?.type === "daily" && (
                    <div class="form-row">
                      <label>Hora (en la zona elegida)</label>
                      <input
                        type="time"
                        value={formatHM(current.schedule.hour, current.schedule.minute)}
                        onInput={(e) => {
                          const { hour, minute } = parseHM((e.target as HTMLInputElement).value);
                          updateCurrent((prev) => ({
                            ...prev,
                            schedule:
                              prev.schedule?.type === "daily"
                                ? { ...prev.schedule, hour, minute }
                                : prev.schedule,
                          }));
                        }}
                      />
                    </div>
                  )}
                  {current.schedule?.type === "weekly" && (
                    <>
                      <div class="form-row">
                        <label>Días</label>
                        <div class="weekday-chips">
                          {WEEKDAY_LABELS.map(({ value, label }) => {
                            const sel = (current.schedule?.type === "weekly" ? current.schedule.weekdays : []).includes(
                              value
                            );
                            return (
                              <label key={value} class="weekday-chip">
                                <input
                                  type="checkbox"
                                  checked={sel}
                                  onChange={() => {
                                    updateCurrent((prev) => {
                                      if (prev.schedule?.type !== "weekly") return prev;
                                      const set = new Set(prev.schedule.weekdays);
                                      if (set.has(value)) set.delete(value);
                                      else set.add(value);
                                      return {
                                        ...prev,
                                        schedule: {
                                          ...prev.schedule,
                                          weekdays: [...set].sort() as DesignerWeekday[],
                                        },
                                      };
                                    });
                                  }}
                                />
                                {label}
                              </label>
                            );
                          })}
                        </div>
                      </div>
                      <div class="form-row">
                        <label>Hora (en la zona elegida)</label>
                        <input
                          type="time"
                          value={
                            current.schedule?.type === "weekly"
                              ? formatHM(current.schedule.hour, current.schedule.minute)
                              : "09:00"
                          }
                          onInput={(e) => {
                            const { hour, minute } = parseHM((e.target as HTMLInputElement).value);
                            updateCurrent((prev) => ({
                              ...prev,
                              schedule:
                                prev.schedule?.type === "weekly"
                                  ? { ...prev.schedule, hour, minute }
                                  : prev.schedule,
                            }));
                          }}
                        />
                      </div>
                    </>
                  )}
                  <div class="form-row">
                    <label>{t.designer.testData}</label>
                    <textarea
                      rows={4}
                      style={{ width: "100%", fontFamily: "monospace", fontSize: "12px" }}
                      value={schedInputDraft}
                      onInput={(e) => {
                        setSchedInputJsonError(null);
                        setSchedInputDraft((e.target as HTMLTextAreaElement).value);
                      }}
                      onBlur={() => {
                        const raw = schedInputDraft.trim();
                        if (raw === "") {
                          setSchedInputJsonError(null);
                          return;
                        }
                        try {
                          JSON.parse(raw);
                          setSchedInputJsonError(null);
                        } catch {
                          setSchedInputJsonError(t.designer.jsonInvalid);
                        }
                      }}
                    />
                    {schedInputJsonError && <p class="panel-error">{schedInputJsonError}</p>}
                    <p class="detail-muted">{t.designer.usedForInstantAndScheduled}</p>
                    <div class="form-row" style={{ marginTop: "8px" }}>
                      <button
                        type="button"
                        class="workflow-filter-btn"
                        disabled={
                          testRunLoading ||
                          !current.id ||
                          !workflows.some((w) => w.id === current.id) ||
                          Boolean(schedInputJsonError)
                        }
                        title={
                          !current.id
                            ? "Guarda el workflow primero"
                            : !workflows.some((w) => w.id === current.id)
                              ? "Guarda el workflow primero"
                              : undefined
                        }
                        onClick={async () => {
                          if (!current?.id) return;
                          setTestRunMessage(null);
                          let input: unknown = {};
                          try {
                            input = schedInputDraft.trim() === "" ? {} : JSON.parse(schedInputDraft);
                          } catch {
                            setTestRunMessage(t.designer.inputJsonInvalid);
                            return;
                          }
                          setTestRunLoading(true);
                          try {
                            const r = await postDesignerTestRun(current.id, { input });
                            setTestRunMessage(`Run iniciado: ${r.workflowId} / ${r.runId} (v${r.version})`);
                          } catch (e) {
                            setTestRunMessage((e as Error).message);
                          } finally {
                            setTestRunLoading(false);
                          }
                        }}
                      >
                        {testRunLoading ? t.designer.starting : t.designer.runTest}
                      </button>
                      {testRunMessage && <span class="detail-muted" style={{ marginLeft: "8px" }}>{testRunMessage}</span>}
                    </div>
                  </div>
                </section>
                )}

                {wizardStep === 3 && (
                <section class="workflow-section">
                  <h3>{t.designer.steps}</h3>
                  <p class="detail-muted">{t.designer.firstStepHint}</p>
                  <button type="button" class="workflow-filter-btn" onClick={handleAddStep}>
                    {t.designer.addStep}
                  </button>
                  {current.steps.length === 0 ? (
                    <p class="detail-muted">{t.designer.needAtLeastOneStep}</p>
                  ) : (
                    <>
                      {advancedMode && (
                      <div class="form-row">
                        <label>Entry step</label>
                        <select
                          value={current.entryStepId}
                          onInput={(e) =>
                            updateCurrent((prev) => ({
                              ...prev,
                              entryStepId: (e.target as HTMLSelectElement).value,
                            }))
                          }
                        >
                          <option value="">{t.designer.choose}</option>
                          {current.steps.map((s) => (
                            <option key={s.id} value={s.id}>
                              {stepDisplayLabel(s)}
                            </option>
                          ))}
                        </select>
                      </div>
                      )}
                      <ul class="workflow-steps-list">
                        {current.steps.map((step) => {
                          const selectedActivity = activities.find(
                            (a) => a.name === (step as any).activityName
                          );
                          const schema = selectedActivity?.inputSchema;

                          return (
                          <li key={step.id} class="workflow-step-editor">
                            <div class="form-row">
                              <label>{t.designer.stepName}</label>
                              <input
                                type="text"
                                value={step.name ?? ""}
                                placeholder={step.id}
                                onInput={(e) =>
                                  handleStepFieldChange(step.id, "name", (e.target as HTMLInputElement).value)
                                }
                              />
                              <button type="button" onClick={() => handleRemoveStep(step.id)}>
                                {t.designer.delete}
                              </button>
                            </div>
                            <div class="form-row">
                              <label>{t.designer.stepType}</label>
                              <select
                                value={step.kind}
                                onInput={(e) => handleStepKindChange(step.id, (e.target as HTMLSelectElement).value as DesignerStepKind)}
                              >
                                {STEP_BLOCK_OPTIONS.map((opt) => (
                                  <option key={opt.kind} value={opt.kind}>
                                    {t.designer[opt.labelKey]}
                                  </option>
                                ))}
                              </select>
                            </div>
                            {advancedMode && (
                            <div class="form-row">
                              <label>Id</label>
                              <input
                                type="text"
                                value={step.id}
                                onInput={(e) =>
                                  handleStepFieldChange(step.id, "id", (e.target as HTMLInputElement).value)
                                }
                              />
                            </div>
                            )}
                            {step.kind === "activity" && (
                            <>
                              <div class="form-row">
                                <label>{t.designer.integration}</label>
                                <select
                                  value={(step as any).integrationModule ?? ""}
                                  onInput={(e) =>
                                    handleStepFieldChange(
                                      step.id,
                                      "integrationModule",
                                      (e.target as HTMLSelectElement).value || undefined,
                                    )
                                  }
                                >
                                  <option value="">{t.designer.allIntegrations}</option>
                                  {Array.from(new Set(activities.map((a) => a.module))).map((mod) => (
                                    <option key={mod} value={mod}>
                                      {mod}
                                    </option>
                                  ))}
                                </select>
                              </div>

                              <div class="form-row">
                                <label>{t.designer.action}</label>
                                <select
                                  value={(step as any).activityName ?? ""}
                                  onInput={(e) => {
                                    const activityName = (e.target as HTMLSelectElement).value;
                                    const activity = activities.find((a) => a.name === activityName);
                                    const defaults = buildDefaultInputFromSchema(activity?.inputSchema);
                                    handleStepFieldChange(step.id, "activityName", activityName);
                                    handleStepFieldChange(step.id, "input", {
                                      ...defaults,
                                      ...((step as any).input ?? {}),
                                    });
                                  }}
                                >
                                  <option value="">(elige una activity)</option>
                                  {Object.entries(
                                    activities
                                      .filter((act) =>
                                        (step as any).integrationModule
                                          ? act.module === (step as any).integrationModule
                                          : true,
                                      )
                                      .reduce<Record<string, ActivityCatalogItem[]>>((acc, act) => {
                                        (acc[act.module] ||= []).push(act);
                                        return acc;
                                      }, {}),
                                  ).map(([module, items]) => (
                                    <optgroup key={module} label={module}>
                                      {items.map((act) => (
                                        <option key={act.name} value={act.name}>
                                          {act.name} {act.version ? `(v${act.version})` : ""}
                                        </option>
                                      ))}
                                    </optgroup>
                                  ))}
                                </select>
                              </div>

                              <div class="form-row">
                                <label>{t.designer.parameters}</label>
                                {schema && schema.type === "object" && (schema as any).properties ? (
                                  <div class="dynamic-fields">
                                    {Object.entries((schema as any).properties).map(
                                      ([propName, propSchema]: [string, any]
                                    ) => {
                                      const required = schema.required?.includes(propName) ?? false;
                                      const value = (step as any).input?.[propName];
                                      const fieldType =
                                        propSchema.type === "number" || propSchema.type === "integer"
                                          ? "number"
                                          : propSchema.type === "boolean"
                                          ? "checkbox"
                                          : "text";

                                      return (
                                        <div class="form-row" key={propName}>
                                          <label>
                                            {propName}
                                            {required ? " *" : ""}
                                          </label>
                                          {fieldType === "checkbox" ? (
                                            <input
                                              type="checkbox"
                                              checked={Boolean(value)}
                                              onInput={(e) =>
                                                handleStepFieldChange(step.id, "input", {
                                                  ...(step as any).input,
                                                  [propName]: (e.target as HTMLInputElement).checked,
                                                })
                                              }
                                            />
                                          ) : (
                                            <input
                                              type={fieldType}
                                              value={value ?? ""}
                                              onInput={(e) => {
                                                const raw = (e.target as HTMLInputElement).value;
                                                let parsed: unknown = raw;
                                              
                                                const trimmed = raw.trim();
                                                const isPlaceholder =
                                                  trimmed.startsWith("{{") && trimmed.endsWith("}}");
                                              
                                                if (!isPlaceholder && fieldType === "number") {
                                                  parsed = raw === "" ? undefined : Number(raw);
                                                }
                                              
                                                handleStepFieldChange(step.id, "input", {
                                                  ...(step as any).input,
                                                  [propName]: parsed,
                                                });
                                              }}
                                            />
                                          )}
                                          {propSchema.description && (
                                            <p class="detail-muted">{propSchema.description}</p>
                                          )}
                                        </div>
                                      );
                                    })}
                                  </div>
                                ) : (
                                  <textarea
                                    value={JSON.stringify((step as any).input ?? {}, null, 2)}
                                    onInput={(e) => {
                                      const text = (e.target as HTMLTextAreaElement).value;
                                      try {
                                        const parsed = text ? JSON.parse(text) : {};
                                        handleStepFieldChange(step.id, "input", parsed);
                                      } catch {
                                      }
                                    }}
                                  />
                                )}
                              </div>
                            </>
                          )}
                          {step.kind === "conditional" && (
                          <>
                            <div class="form-row">
                              <label>{t.designer.path}</label>
                              <input
                                type="text"
                                placeholder="input.amount o steps.step-1.result.status"
                                value={(step as any).path ?? ""}
                                onInput={(e) => {
                                  const path = (e.target as HTMLInputElement).value;
                                  const op = (step as any).operator ?? "===";
                                  const right = (step as any).right ?? "";
                                  const expression = path && right ? `${path} ${op} ${right}` : "";
                                  handleStepFieldChange(step.id, "path", path);
                                  handleStepFieldChange(step.id, "expression", expression);
                                }}
                              />
                            </div>

                            <div class="form-row">
                              <label>{t.designer.operator}</label>
                              <select
                                value={(step as any).operator ?? "==="}
                                onInput={(e) => {
                                  const op = (e.target as HTMLSelectElement).value;
                                  const path = (step as any).path ?? "";
                                  const right = (step as any).right ?? "";
                                  const expression = path && right ? `${path} ${op} ${right}` : "";
                                  handleStepFieldChange(step.id, "operator", op);
                                  handleStepFieldChange(step.id, "expression", expression);
                                }}
                              >
                                <option value="===">===</option>
                                <option value="!==">!==</option>
                                <option value=">">&gt;</option>
                                <option value="<">&lt;</option>
                                <option value=">=">&gt;=</option>
                                <option value="<=">&lt;=</option>
                              </select>
                            </div>

                            <div class="form-row">
                              <label>{t.designer.value}</label>
                              <input
                                type="text"
                                placeholder="1000, 'completed', true..."
                                value={(step as any).right ?? ""}
                                onInput={(e) => {
                                  const right = (e.target as HTMLInputElement).value;
                                  const path = (step as any).path ?? "";
                                  const op = (step as any).operator ?? "===";
                                  const expression = path && right ? `${path} ${op} ${right}` : "";
                                  handleStepFieldChange(step.id, "right", right);
                                  handleStepFieldChange(step.id, "expression", expression);
                                }}
                              />
                            </div>

                            <div class="form-row">
                              <label>{t.designer.thenStep}</label>
                              <select
                                value={(step as any).thenNext ?? ""}
                                onInput={(e) =>
                                  handleStepFieldChange(
                                    step.id,
                                    "thenNext",
                                    (e.target as HTMLSelectElement).value || null,
                                  )
                                }
                              >
                                <option value="">{t.designer.endStep}</option>
                                {current.steps
                                  .filter((s) => s.id !== step.id)
                                  .map((s) => (
                                    <option key={s.id} value={s.id}>
                                      {s.id}
                                    </option>
                                  ))}
                              </select>
                            </div>

                            <div class="form-row">
                              <label>{t.designer.elseStep}</label>
                              <select
                                value={(step as any).elseNext ?? ""}
                                onInput={(e) =>
                                  handleStepFieldChange(
                                    step.id,
                                    "elseNext",
                                    (e.target as HTMLSelectElement).value || null,
                                  )
                                }
                              >
                                <option value="">{t.designer.endStep}</option>
                                {current.steps
                                  .filter((s) => s.id !== step.id)
                                  .map((s) => (
                                    <option key={s.id} value={s.id}>
                                      {s.id}
                                    </option>
                                  ))}
                              </select>
                            </div>
                          </>
                        )}
                        {step.kind === "sleep" && (
                              <div class="form-row">
                                <label>{t.designer.waitDuration}</label>
                                <input
                                  type="number"
                                  value={(step as any).milliseconds ?? 0}
                                  onInput={(e) =>
                                    handleStepFieldChange(
                                      step.id,
                                      "milliseconds",
                                      Number((e.target as HTMLInputElement).value) || 0,
                                    )
                                  }
                                />
                              </div>
                        )}
                        {step.kind === "signal" && (
                              <div class="form-row">
                                <label>{t.designer.signalLabel}</label>
                                <input
                                  type="text"
                                  value={(step as any).signalName ?? ""}
                                  onInput={(e) =>
                                    handleStepFieldChange(
                                      step.id,
                                      "signalName",
                                      (e.target as HTMLInputElement).value,
                                    )
                                  }
                                />
                              </div>
                        )}
                        {step.kind === "retry" && (
                          <>
                            <div class="form-row">
                              <label>{t.designer.maxAttempts}</label>
                              <input
                                type="number"
                                min={1}
                                max={50}
                                value={(step as any).maxAttempts ?? 3}
                                onInput={(e) =>
                                  handleStepFieldChange(
                                    step.id,
                                    "maxAttempts",
                                    Math.max(1, Number((e.target as HTMLInputElement).value) || 1),
                                  )
                                }
                              />
                            </div>
                            <div class="form-row">
                              <label>{t.designer.backoffMs}</label>
                              <input
                                type="number"
                                min={0}
                                value={(step as any).backOffMs ?? ""}
                                placeholder="(opcional)"
                                onInput={(e) => {
                                  const v = (e.target as HTMLInputElement).value;
                                  handleStepFieldChange(
                                    step.id,
                                    "backOffMs",
                                    v === "" ? undefined : Math.max(0, Number(v) || 0),
                                  );
                                }}
                              />
                            </div>
                            <div class="form-row">
                              <label>{t.designer.retryTarget}</label>
                              <select
                                value={(step as any).targetStepId ?? ""}
                                onInput={(e) =>
                                  handleStepFieldChange(
                                    step.id,
                                    "targetStepId",
                                    (e.target as HTMLSelectElement).value,
                                  )
                                }
                              >
                                <option value="">(elige activity step)</option>
                                {current.steps
                                  .filter((s) => s.id !== step.id && s.kind === "activity")
                                  .map((s) => (
                                    <option key={s.id} value={s.id}>
                                      {s.id}
                                    </option>
                                  ))}
                              </select>
                            </div>
                          </>
                        )}
                        {step.kind === "parallel" && (
                        <>
                          {Array.isArray((step as any).branches) &&
                            (step as any).branches.map((_branch: string[], idx: number) => (
                              <div class="form-row" key={idx}>
                                <label>{t.designer.parallelBranch} {idx + 1}</label>
                                <select
                                  multiple
                                  onChange={(e) => {
                                    const selected = Array.from(
                                      (e.target as HTMLSelectElement).selectedOptions
                                    ).map((o) => o.value);
                                    const allBranches = [...(((step as any).branches as string[][]) ?? [])];
                                    allBranches[idx] = selected;
                                    handleStepFieldChange(step.id, "branches", allBranches);
                                  }}
                                >
                                  {current.steps
                                    .filter((s) => s.id !== step.id && s.kind === "activity")
                                    .map((s) => (
                                      <option key={s.id} value={s.id}>
                                        {s.id}
                                      </option>
                                    ))}
                                </select>
                              </div>
                            ))}

                          <div class="form-row">
                            <button
                              type="button"
                              class="workflow-filter-btn"
                              onClick={() => {
                                const existing = ((step as any).branches as string[][]) ?? [];
                                const updated = [...existing, []];
                                handleStepFieldChange(step.id, "branches", updated);
                              }}
                            >
                              {t.designer.addBranch}
                            </button>
                          </div>
                        </>
                      )}
                            <div class="form-row">
                              <label>{t.designer.nextStep}</label>
                              <select
                                value={step.next ?? ""}
                                onInput={(e) =>
                                  handleStepFieldChange(
                                    step.id,
                                    "next",
                                    (e.target as HTMLSelectElement).value || null,
                                  )
                                }
                              >
                                <option value="">{t.designer.endStep}</option>
                                {current.steps
                                  .filter((s) => s.id !== step.id)
                                  .map((s) => (
                                    <option key={s.id} value={s.id}>
                                      {s.id}
                                    </option>
                                  ))}
                              </select>
                            </div>
                          </li>
                          );
                        })}
                      </ul>
                    </>
                  )}
                </section>
                )}

                {advancedMode && (
                <section class="workflow-section">
                  <h3>{t.designer.advancedMode}</h3>
                  <p class="detail-muted">{t.designer.payloadPreview}</p>
                  <pre
                    class="detail-muted"
                    style={{
                      whiteSpace: "pre-wrap",
                      fontSize: "12px",
                      maxHeight: "240px",
                      overflow: "auto",
                      padding: "8px",
                      background: "var(--panel-bg, #1a1a1e)",
                      borderRadius: "6px",
                    }}
                  >
                    {current ? JSON.stringify(current, null, 2) : ""}
                  </pre>
                </section>
                )}

                <section class="workflow-section">
                  <button type="button" class="workflow-filter-btn" onClick={handleSave}>
                    {editTarget === "template" ? t.designer.saveTemplate : t.designer.saveWorkflow}
                  </button>
                  <button
                    type="button"
                    class="workflow-filter-btn"
                    onClick={() => {
                      setMode("list");
                      setCurrent(null);
                    }}
                  >
                    {t.designer.cancel}
                  </button>
                </section>
              </>
            )}
          </div>
        ) : (
          <div class="panel">
            <p class="detail-muted">
              {t.designer.chooseLeft}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}